-- Fix wagtailsearch_indexentry table
-- Run this in the database shell: docker compose exec db psql -U postgres -d portfolio_strategist -f fix_wagtailsearch_table.sql

-- First, check if table exists
SELECT EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_schema = 'public' 
    AND table_name = 'wagtailsearch_indexentry'
);

-- If table doesn't exist, create it (uncomment if needed):
/*
CREATE TABLE "wagtailsearch_indexentry" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "object_id" varchar(50) NOT NULL,
    "title_norm" double precision NOT NULL,
    "content_type_id" integer NOT NULL,
    "autocomplete" tsvector NOT NULL,
    "title" tsvector NOT NULL,
    "body" tsvector NOT NULL
);

-- Add constraints and indexes
ALTER TABLE "wagtailsearch_indexentry" 
    ADD CONSTRAINT "wagtailsearch_indexentry_content_type_id_object_i_bcd7ba73_uniq" 
    UNIQUE ("content_type_id", "object_id");

ALTER TABLE "wagtailsearch_indexentry" 
    ADD CONSTRAINT "wagtailsearch_indexe_content_type_id_62ed694f_fk_django_co" 
    FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") 
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "wagtailsearch_indexentry_content_type_id_62ed694f" 
    ON "wagtailsearch_indexentry" ("content_type_id");

CREATE INDEX "wagtailsear_autocom_476c89_gin" 
    ON "wagtailsearch_indexentry" USING gin ("autocomplete");

CREATE INDEX "wagtailsear_title_9caae0_gin" 
    ON "wagtailsearch_indexentry" USING gin ("title");

CREATE INDEX "wagtailsear_body_90c85d_gin" 
    ON "wagtailsearch_indexentry" USING gin ("body");
*/

-- Verify table structure
\d wagtailsearch_indexentry

-- Check permissions
SELECT grantee, privilege_type 
FROM information_schema.role_table_grants 
WHERE table_name = 'wagtailsearch_indexentry';

-- Grant permissions if needed (uncomment if needed):
-- GRANT ALL PRIVILEGES ON TABLE wagtailsearch_indexentry TO postgres;
-- GRANT ALL PRIVILEGES ON SEQUENCE wagtailsearch_indexentry_id_seq TO postgres;

