# Generated by Django 5.1.5 on 2025-12-03 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web", "0003_patch_djstripe_tax_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquationCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Requires premium subscription"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Equation Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Equation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "formula_latex",
                    models.TextField(help_text="LaTeX representation of the formula"),
                ),
                (
                    "formula_text",
                    models.CharField(
                        help_text="Plain text representation", max_length=500
                    ),
                ),
                (
                    "parameters_json",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object with parameter definitions: {name: {type, default, min, max, description}}",
                    ),
                ),
                (
                    "implementation_type",
                    models.CharField(
                        choices=[
                            ("python", "Python Function"),
                            ("javascript", "JavaScript Function"),
                            ("formula", "Mathematical Formula"),
                        ],
                        default="python",
                        max_length=50,
                    ),
                ),
                (
                    "implementation_code",
                    models.TextField(
                        blank=True,
                        help_text="Code to evaluate the equation (Python or JavaScript)",
                    ),
                ),
                (
                    "use_cases",
                    models.TextField(blank=True, help_text="When to use this equation"),
                ),
                (
                    "references",
                    models.TextField(blank=True, help_text="References and citations"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Requires premium subscription"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured section"
                    ),
                ),
                (
                    "supports_graph",
                    models.BooleanField(default=False, help_text="Can generate graphs"),
                ),
                (
                    "graph_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("line", "Line Chart"),
                            ("scatter", "Scatter Plot"),
                            ("histogram", "Histogram"),
                            ("distribution", "Probability Distribution"),
                            ("surface", "3D Surface"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "graph_config_json",
                    models.JSONField(
                        default=dict,
                        help_text="Graph configuration: {x_label, y_label, x_range, y_range, etc.}",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equations",
                        to="web.equationcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EquationRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("builds_on", "Builds On"),
                            ("integrates_with", "Integrates With"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="web.equation",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="web.equation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equation Relationship",
                "verbose_name_plural": "Equation Relationships",
                "unique_together": {("source", "target", "relationship_type")},
            },
        ),
        migrations.AddField(
            model_name="equation",
            name="related_equations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reference formulas that build on or integrate with this one",
                related_name="related_backlinks",
                through="web.EquationRelationship",
                to="web.equation",
            ),
        ),
        migrations.CreateModel(
            name="EquationVariable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "symbol",
                    models.CharField(
                        help_text="Mathematical symbol (e.g., μ, σ)", max_length=20
                    ),
                ),
                ("description", models.TextField()),
                (
                    "variable_type",
                    models.CharField(
                        choices=[
                            ("float", "Number"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("string", "Text"),
                        ],
                        default="float",
                        max_length=50,
                    ),
                ),
                ("default_value", models.CharField(blank=True, max_length=200)),
                (
                    "min_value",
                    models.CharField(
                        blank=True, help_text="Minimum allowed value", max_length=200
                    ),
                ),
                (
                    "max_value",
                    models.CharField(
                        blank=True, help_text="Maximum allowed value", max_length=200
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        blank=True, help_text="Step size for sliders", max_length=200
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measurement", max_length=50
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "equation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="web.equation",
                    ),
                ),
            ],
            options={
                "ordering": ["equation", "order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="equation",
            index=models.Index(
                fields=["category", "is_featured"],
                name="web_equatio_categor_b21238_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equation",
            index=models.Index(fields=["slug"], name="web_equatio_slug_8f1383_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="equationvariable",
            unique_together={("equation", "name")},
        ),
    ]
