# Generated by Django 5.1.5 on 2025-12-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equation',
            name='related_equations',
        ),
        migrations.DeleteModel(
            name='EquationRelationship',
        ),
    ]
