# Generated by Django 5.1.5 on 2025-12-02 18:57

from django.db import migrations


def bootstrap_wagtail_blog_content(apps, schema_editor):
    # Import inside function so migrations don't evaluate the module during checks
    from apps.content.management.commands.bootstrap_content import bootstrap_initial_content

    bootstrap_initial_content()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_blogindexpage_social_image_blogpage_social_image_and_more"),
        # Ensure all Wagtail core migrations (including the ones that add
        # wagtailcore_page.latest_revision_id) have been applied before we
        # attempt to import and query Wagtail models inside this data migration.
        ("wagtailcore", "0094_alter_page_locale"),
        # Publishing the bootstrap content triggers search indexing, so make sure
        # the Wagtail search tables exist as well.
        ("wagtailsearch", "0008_remove_query_and_querydailyhits_models"),
    ]

    operations = [
        migrations.RunPython(bootstrap_wagtail_blog_content, noop),
    ]
