# Generated by Django 5.1.5 on 2025-12-03 01:48

from django.db import migrations


def fix_submitted_for_moderation_nulls(apps, schema_editor):
    """Set all NULL submitted_for_moderation values to False"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if the table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'wagtailcore_revision'
            )
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            print("wagtailcore_revision table does not exist, skipping fix...")
            return
        
        # Check if the column exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'wagtailcore_revision'
                AND column_name = 'submitted_for_moderation'
            )
        """)
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            print("submitted_for_moderation column does not exist, skipping fix...")
            return
        
        cursor.execute(
            "UPDATE wagtailcore_revision SET submitted_for_moderation = FALSE WHERE submitted_for_moderation IS NULL"
        )
        # Set default value for the column
        cursor.execute(
            "ALTER TABLE wagtailcore_revision ALTER COLUMN submitted_for_moderation SET DEFAULT FALSE"
        )


def reverse_fix(apps, schema_editor):
    """Reverse migration - remove default (but keep existing values)"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if the table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'wagtailcore_revision'
            )
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            return
        
        # Check if the column exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'wagtailcore_revision'
                AND column_name = 'submitted_for_moderation'
            )
        """)
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            return
        
        cursor.execute(
            "ALTER TABLE wagtailcore_revision ALTER COLUMN submitted_for_moderation DROP DEFAULT"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_bootstrap_initial_blog_content'),
        ('wagtailcore', '0069_log_entry_jsonfield'),  # Ensure Wagtail migrations are applied
    ]

    operations = [
        migrations.RunPython(fix_submitted_for_moderation_nulls, reverse_fix),
    ]
