# Generated by Django 5.1.5 on 2025-12-01 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLoanAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='loan_analyses/')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('individual_amounts', models.JSONField(default=dict)),
                ('total_amounts', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal Loan Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('stock_data', models.JSONField(default=dict)),
                ('ratios_table', models.JSONField(default=dict)),
                ('ai_assessment', models.TextField(blank=True)),
                ('forecast_data', models.JSONField(blank=True, default=dict, null=True)),
                ('news_html', models.TextField(blank=True)),
                ('forecast_days', models.IntegerField(default=365)),
                ('equation_type', models.CharField(default='Geometric Brownian Motion External Macroeconomic Factors', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('share_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forecast_summary', models.JSONField(default=dict)),
                ('alert_enabled', models.BooleanField(default=False)),
                ('alert_email', models.EmailField(blank=True, max_length=254)),
                ('alert_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_plans', to=settings.AUTH_USER_MODEL)),
                ('stock_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='stock_analysis.stockanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['user', '-analysis_date'], name='stock_analy_user_id_0a5681_idx'),
        ),
        migrations.AddIndex(
            model_name='stockanalysis',
            index=models.Index(fields=['symbol'], name='stock_analy_symbol_c3789b_idx'),
        ),
    ]
