# Generated by Django 5.1.5 on 2025-12-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0005_periodic_stock_refresh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockwatchsnapshot',
            options={'ordering': ['symbol'], 'verbose_name': 'Stock Watch Snapshot (Public)', 'verbose_name_plural': 'Stock Watch Snapshots (Public)'},
        ),
    ]
