# Generated by Django 5.1.5 on 2025-05-16 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('earnings', 'Earnings'), ('government', 'Government'), ('retirement', 'Retirement'), ('insurance', 'Insurance'), ('debt', 'Debt'), ('investments', 'Investments'), ('budgeting', 'Budgeting'), ('assets', 'Assets'), ('credit_score', 'Credit Score')], max_length=50)),
                ('sub_record_type', models.CharField(choices=[('earnings', [('pay_stubs', 'Pay stubs'), ('w2_forms', 'W-2 forms'), ('1099_forms', '1099 forms (for freelance or contract work)'), ('bank_statements', 'Bank statements showing direct deposits'), ('tax_returns', 'Tax returns (income sections)'), ('bonus_commission', 'Bonus or commission statements'), ('profit_sharing', 'Profit-sharing statements'), ('dividend_income', 'Dividend income records'), ('royalty_income', 'Royalty income statements'), ('alimony_child_support', 'Alimony or child support records')]), ('government', [('social_security', 'Social Security statements'), ('tax_assessment', 'Tax assessment notices'), ('gov_benefits', 'Government benefit statements'), ('stimulus_payments', 'Stimulus payment records'), ('irs_notices', 'IRS notices or correspondence'), ('property_tax_bills', 'Property tax bills'), ('fafsa_records', 'FAFSA records (for student aid)'), ('veterans_benefits', 'Veterans benefits statements'), ('medicare_medicaid', 'Medicare/Medicaid statements'), ('court_ordered', 'Court-ordered financial documents')]), ('retirement', [('401k_statements', '401(k) statements'), ('ira_statements', 'IRA (Traditional or Roth) statements'), ('pension_plan_summaries', 'Pension plan summaries'), ('annuity_contracts', 'Annuity contracts'), ('ss_benefit_estimates', 'Social Security benefit estimates'), ('retirement_contributions', 'Retirement account contribution records'), ('rmd_notices', 'Required Minimum Distribution (RMD) notices'), ('rollover_docs', 'Rollover documentation'), ('beneficiary_designations', 'Beneficiary designation forms'), ('retirement_withdrawals', 'Retirement plan withdrawal records')]), ('insurance', [('policy_docs', 'Policy documents (life, health, auto, home, etc.)'), ('premium_receipts', 'Premium payment receipts'), ('claims_history', 'Claims history records'), ('deductible_coverage', 'Deductible and coverage summaries'), ('insurance_id_cards', 'Insurance ID cards'), ('declarations_pages', 'Declarations pages'), ('renewal_notices', 'Renewal notices'), ('settlement_offers', 'Settlement offers'), ('umbrella_policy', 'Umbrella insurance policies'), ('long_term_care', 'Long-term care insurance documents')]), ('debt', [('loan_agreements', 'Loan agreements (personal, auto, student, etc.)'), ('credit_card_statements', 'Credit card statements'), ('mortgage_statements', 'Mortgage statements'), ('debt_collection_notices', 'Debt collection notices'), ('payment_history', 'Payment history records'), ('promissory_notes', 'Promissory notes'), ('debt_settlement', 'Debt settlement agreements'), ('bankruptcy_filings', 'Bankruptcy filings'), ('credit_counseling', 'Credit counseling reports'), ('cosigned_loans', 'Co-signed loan documents')]), ('investments', [('brokerage_statements', 'Brokerage account statements'), ('stock_bond_certificates', 'Stock or bond certificates'), ('mutual_fund_statements', 'Mutual fund statements'), ('real_estate_investments', 'Real estate investment records'), ('crypto_transactions', 'Cryptocurrency transaction history'), ('investment_performance', 'Investment performance reports'), ('capital_gains_losses', 'Capital gains/loss statements'), ('drip_records', 'Dividend reinvestment plans (DRIPs)'), ('prospectuses', 'Prospectuses for investments'), ('partnership_investments', 'Partnership or LLC investment records')]), ('budgeting', [('monthly_budgets', 'Monthly budget spreadsheets'), ('expense_tracking', 'Expense tracking logs'), ('savings_goals', 'Savings goal trackers'), ('spending_breakdowns', 'Spending category breakdowns'), ('cash_flow_statements', 'Cash flow statements'), ('financial_planning_worksheets', 'Financial planning worksheets'), ('subscriptions', 'Subscription or membership records'), ('utility_bills', 'Utility bills'), ('grocery_dining_logs', 'Grocery and dining expense logs'), ('entertainment_spending', 'Entertainment and leisure spending records')]), ('assets', [('property_deeds', 'Property deeds (real estate)'), ('vehicle_titles', 'Vehicle titles'), ('appraisals', 'Appraisals (jewelry, art, etc.)'), ('inventory', 'Inventory of personal belongings'), ('business_docs', 'Business ownership documents'), ('trust_fund_statements', 'Trust fund statements'), ('inheritance_records', 'Inheritance records'), ('collectibles', 'Collectibles valuation reports'), ('intellectual_property', 'Intellectual property documents'), ('lease_agreements', 'Lease agreements (if renting out property)')]), ('credit_score', [('credit_reports', 'Credit reports (Equifax, Experian, TransUnion)'), ('credit_monitoring', 'Credit monitoring service updates'), ('credit_card_utilization', 'Credit card utilization summaries'), ('loan_approvals_denials', 'Loan approval/denial letters'), ('inquiry_records', 'Hard and soft inquiry records'), ('dispute_letters', 'Dispute resolution letters'), ('credit_score_improvement', 'Credit score improvement plans'), ('identity_theft_reports', 'Identity theft reports'), ('credit_counseling_notes', 'Credit counseling session notes'), ('payment_history_reports', 'Payment history reports (on-time/late payments)')])], max_length=50)),
                ('year', models.IntegerField(choices=[(1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049'), (2050, '2050'), (2051, '2051'), (2052, '2052'), (2053, '2053'), (2054, '2054'), (2055, '2055'), (2056, '2056'), (2057, '2057'), (2058, '2058'), (2059, '2059'), (2060, '2060'), (2061, '2061'), (2062, '2062'), (2063, '2063'), (2064, '2064'), (2065, '2065'), (2066, '2066'), (2067, '2067'), (2068, '2068'), (2069, '2069'), (2070, '2070'), (2071, '2071'), (2072, '2072'), (2073, '2073'), (2074, '2074'), (2075, '2075'), (2076, '2076'), (2077, '2077'), (2078, '2078'), (2079, '2079'), (2080, '2080'), (2081, '2081'), (2082, '2082'), (2083, '2083'), (2084, '2084'), (2085, '2085'), (2086, '2086'), (2087, '2087'), (2088, '2088'), (2089, '2089'), (2090, '2090'), (2091, '2091'), (2092, '2092'), (2093, '2093'), (2094, '2094'), (2095, '2095'), (2096, '2096'), (2097, '2097'), (2098, '2098'), (2099, '2099')])),
                ('document', models.FileField(upload_to='financial_documents/')),
                ('processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='records.financialdocument')),
            ],
        ),
    ]
