# Generated by Django 5.1.5 on 2025-12-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='record_type',
            field=models.CharField(choices=[('earnings', 'Earnings'), ('government', 'Governemnt'), ('retirement', 'Retirement'), ('insurance', 'Insurance'), ('debt', 'Debt'), ('investments', 'Investments'), ('budgeting', 'Budgeting'), ('assets', 'Assets'), ('credit_score', 'Credit Score')], max_length=50),
        ),
    ]
