# Generated by Django 5.1.5 on 2025-03-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdocument',
            name='name',
        ),
    ]
