# Generated by Django 5.1.5 on 2025-12-01 19:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_financialdocument_record_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('plaid', 'Plaid'), ('yodlee', 'Yodlee'), ('finicity', 'Finicity (Mastercard)'), ('mx', 'MX'), ('stripe_financial', 'Stripe Financial Connections'), ('flinks', 'Flinks'), ('akoya', 'Akoya')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, help_text='Encrypted API key', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='Encrypted API secret', max_length=255)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('development', 'Development'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('webhook_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_account_id', models.CharField(db_index=True, help_text='Account ID from aggregation provider', max_length=255)),
                ('provider_item_id', models.CharField(db_index=True, help_text='Item ID from aggregation provider (e.g., Plaid item_id)', max_length=255)),
                ('access_token', models.TextField(help_text='Encrypted access token for fetching data')),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_id', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('depository', 'Bank Account'), ('credit', 'Credit Card'), ('loan', 'Loan'), ('investment', 'Investment Account'), ('brokerage', 'Brokerage Account'), ('retirement', 'Retirement Account'), ('other', 'Other')], max_length=50)),
                ('account_subtype', models.CharField(blank=True, max_length=100)),
                ('account_number_masked', models.CharField(blank=True, help_text='Last 4 digits or masked account number', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_accounts', to='records.aggregationprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('security_id', models.CharField(blank=True, max_length=255)),
                ('security_name', models.CharField(blank=True, max_length=255)),
                ('security_ticker', models.CharField(blank=True, max_length=20)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField(db_index=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to='records.linkedaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_id', models.CharField(db_index=True, max_length=255)),
                ('security_name', models.CharField(max_length=255)),
                ('security_ticker', models.CharField(blank=True, max_length=20)),
                ('security_type', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('as_of_date', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='records.linkedaccount')),
            ],
            options={
                'ordering': ['-as_of_date', 'security_name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Provider transaction ID', max_length=255)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('transfer', 'Transfer')], max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('category_detail', models.CharField(blank=True, max_length=255)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('payment_channel', models.CharField(blank=True, max_length=50)),
                ('pending', models.BooleanField(default=False)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='records.linkedaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('mortgage', 'Mortgage'), ('auto_loan', 'Auto Loan'), ('student_loan', 'Student Loan'), ('personal_loan', 'Personal Loan'), ('other', 'Other')], max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual percentage rate', max_digits=5, null=True)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('as_of_date', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_accounts', to='records.linkedaccount')),
            ],
            options={
                'ordering': ['-as_of_date'],
            },
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('accounts_synced', models.IntegerField(default=0)),
                ('transactions_synced', models.IntegerField(default=0)),
                ('balances_synced', models.IntegerField(default=0)),
                ('holdings_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='records.linkedaccount')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit for credit cards', max_digits=15, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('balance_date', models.DateTimeField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='records.linkedaccount')),
            ],
            options={
                'ordering': ['-balance_date'],
                'get_latest_by': 'balance_date',
            },
        ),
        migrations.AddIndex(
            model_name='linkedaccount',
            index=models.Index(fields=['user', 'status'], name='records_lin_user_id_6b931b_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedaccount',
            index=models.Index(fields=['provider', 'provider_account_id'], name='records_lin_provide_c259ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linkedaccount',
            unique_together={('user', 'provider', 'provider_account_id')},
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['account', '-date'], name='records_inv_account_437ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['date', 'transaction_type'], name='records_inv_date_7d5fcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmenttransaction',
            unique_together={('account', 'transaction_id')},
        ),
        migrations.AddIndex(
            model_name='investmentholding',
            index=models.Index(fields=['account', '-as_of_date'], name='records_inv_account_033a56_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentholding',
            index=models.Index(fields=['security_ticker'], name='records_inv_securit_a5718a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentholding',
            unique_together={('account', 'security_id', 'as_of_date')},
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['account', '-date'], name='records_fin_account_e5a7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['date', 'category'], name='records_fin_date_07990e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['account', 'pending'], name='records_fin_account_4455e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialtransaction',
            unique_together={('account', 'transaction_id')},
        ),
        migrations.AddIndex(
            model_name='debtaccount',
            index=models.Index(fields=['account', '-as_of_date'], name='records_deb_account_92cbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['account', '-started_at'], name='records_dat_account_a3fdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='datasynclog',
            index=models.Index(fields=['status', '-started_at'], name='records_dat_status_0203db_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['account', '-balance_date'], name='records_acc_account_b50610_idx'),
        ),
    ]
