# Generated by Django 5.1.5 on 2025-12-01 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_aggregationprovider_linkedaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BondAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='Bond Investment', max_length=255)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coupon_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('years_to_maturity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_frequency', models.IntegerField(choices=[(1, 'Annually'), (2, 'Semi-Annually'), (4, 'Quarterly'), (12, 'Monthly')], default=2)),
                ('forecast_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_account', models.ForeignKey(blank=True, help_text='Optional: Link to Plaid account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.linkedaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CDAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='CD Account', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('compounding_frequency', models.IntegerField(choices=[(1, 'Annually'), (2, 'Semi-Annually'), (4, 'Quarterly'), (12, 'Monthly'), (365, 'Daily')], default=12)),
                ('forecast_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_account', models.ForeignKey(blank=True, help_text='Optional: Link to Plaid account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.linkedaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cd_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='Savings Account', max_length=255)),
                ('initial_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('compounding_frequency', models.IntegerField(choices=[(1, 'Annually'), (2, 'Semi-Annually'), (4, 'Quarterly'), (12, 'Monthly'), (365, 'Daily')], default=12)),
                ('forecast_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_account', models.ForeignKey(blank=True, help_text='Optional: Link to Plaid account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.linkedaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StocksAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('share_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('forecast_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_account', models.ForeignKey(blank=True, help_text='Optional: Link to Plaid account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.linkedaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
