# Generated by Django 5.1.5 on 2025-12-17 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_budgetscenario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('due_day', models.IntegerField(help_text='Day of month (1-31) or day of week (1-7) for weekly')),
                ('is_autopay', models.BooleanField(default=False)),
                ('autopay_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_paid_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('yearly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('color', models.CharField(default='#3498db', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Budget Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category_budgets', models.JSONField(blank=True, default=dict)),
                ('actual_spending', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_by_category', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('bill_due', 'Bill Due'), ('goal_milestone', 'Goal Milestone'), ('recurring_transaction', 'Recurring Transaction'), ('tax_deadline', 'Tax Deadline'), ('subscription_renewal', 'Subscription Renewal'), ('payment_reminder', 'Payment Reminder'), ('custom', 'Custom Event')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('reminder_date', models.DateField(blank=True, help_text='Date to send reminder', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, help_text="e.g., 'monthly', 'yearly', 'weekly'", max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal_type', models.CharField(choices=[('savings', 'Savings Goal'), ('investment', 'Investment Goal'), ('debt_payoff', 'Debt Payoff Goal'), ('emergency_fund', 'Emergency Fund'), ('retirement', 'Retirement Goal'), ('purchase', 'Major Purchase'), ('education', 'Education Fund'), ('other', 'Other')], max_length=50)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Planned monthly contribution', max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=5, help_text='1-10, where 10 is highest priority')),
                ('progress_history', models.JSONField(blank=True, default=list, help_text='Historical progress snapshots')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialHealthScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='Overall financial health score (0-100)')),
                ('savings_score', models.IntegerField(default=0, help_text='Savings adequacy score')),
                ('debt_score', models.IntegerField(default=0, help_text='Debt management score')),
                ('investment_score', models.IntegerField(default=0, help_text='Investment health score')),
                ('budget_score', models.IntegerField(default=0, help_text='Budget adherence score')),
                ('emergency_fund_score', models.IntegerField(default=0, help_text='Emergency fund adequacy')),
                ('credit_score_health', models.IntegerField(default=0, help_text='Credit score health')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Detailed financial metrics')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Actionable recommendations')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculation_version', models.CharField(default='1.0', max_length=50)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'get_latest_by': 'calculated_at',
            },
        ),
        migrations.CreateModel(
            name='FinancialNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('goal_progress', 'Goal Progress Update'), ('goal_milestone', 'Goal Milestone Reached'), ('goal_deadline', 'Goal Deadline Approaching'), ('low_balance', 'Low Account Balance'), ('high_spending', 'High Spending Alert'), ('bill_due', 'Bill Due Reminder'), ('investment_alert', 'Investment Price Alert'), ('budget_exceeded', 'Budget Exceeded'), ('transaction_large', 'Large Transaction'), ('account_sync_error', 'Account Sync Error'), ('subscription_renewal', 'Subscription Renewal'), ('tax_reminder', 'Tax Filing Reminder'), ('credit_score_change', 'Credit Score Change'), ('market_alert', 'Market Alert'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to for action')),
                ('action_label', models.CharField(blank=True, help_text='Label for action button', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('comparison_data', models.JSONField(blank=True, default=dict, help_text='Stores comparison results')),
                ('compared_items', models.JSONField(blank=True, default=list)),
                ('comparison_type', models.CharField(help_text="e.g., 'stocks', 'portfolios', 'time_periods'", max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('next_occurrence', models.DateField()),
                ('last_occurrence', models.DateField(blank=True, null=True)),
                ('is_detected', models.BooleanField(default=False, help_text='True if auto-detected, False if manually created')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence in pattern detection (0-100)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_occurrence'],
            },
        ),
        migrations.CreateModel(
            name='RetirementPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Retirement Plan', max_length=255)),
                ('current_age', models.IntegerField()),
                ('retirement_age', models.IntegerField()),
                ('current_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_annual_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('desired_retirement_income', models.DecimalField(decimal_places=2, help_text='Annual income needed in retirement', max_digits=15)),
                ('retirement_savings_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated or manual goal', max_digits=15, null=True)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employer_match_percent', models.DecimalField(decimal_places=2, default=0, help_text='Employer 401k match percentage', max_digits=5)),
                ('employer_match_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Max employer match amount', max_digits=15, null=True)),
                ('expected_return_rate', models.DecimalField(decimal_places=2, default=7.0, help_text='Expected annual return percentage', max_digits=5)),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Expected inflation rate', max_digits=5)),
                ('social_security_benefit', models.DecimalField(blank=True, decimal_places=2, help_text='Expected monthly SS benefit', max_digits=15, null=True)),
                ('projections', models.JSONField(blank=True, default=dict, help_text='Year-by-year projections')),
                ('scenarios', models.JSONField(blank=True, default=list, help_text='Different scenario calculations')),
                ('analysis', models.JSONField(blank=True, default=dict, help_text='Analysis results and recommendations')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxOptimizationStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(help_text="e.g., 'tax_loss_harvesting', 'capital_gains_optimization'", max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('applicable_securities', models.JSONField(blank=True, default=list, help_text='List of securities this applies to')),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('tax_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-tax_year', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='budgetscenario',
            new_name='records_bud_user_id_8bafcb_idx',
            old_name='records_bud_user_id_d6e2d8_idx',
        ),
        migrations.AlterField(
            model_name='budgetscenario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account to pay from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.linkedaccount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='records.budgetcategory'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialcalendarevent',
            name='related_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.linkedaccount'),
        ),
        migrations.AddField(
            model_name='financialcalendarevent',
            name='related_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.bill'),
        ),
        migrations.AddField(
            model_name='financialcalendarevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.linkedaccount'),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='linked_savings_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.savingsassessment'),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='linked_stocks_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.stocksassessment'),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialcalendarevent',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.financialgoal'),
        ),
        migrations.AddField(
            model_name='financialhealthscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialnotification',
            name='related_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='records.linkedaccount'),
        ),
        migrations.AddField(
            model_name='financialnotification',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='records.financialgoal'),
        ),
        migrations.AddField(
            model_name='financialnotification',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='records.financialtransaction'),
        ),
        migrations.AddField(
            model_name='financialnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfoliocomparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comparisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='records.linkedaccount'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='matching_transactions',
            field=models.ManyToManyField(blank=True, related_name='recurring_patterns', to='records.financialtransaction'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retirementplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxoptimizationstrategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'is_active'], name='records_bil_user_id_b50c21_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['next_due_date'], name='records_bil_next_du_8c9fef_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['user', 'is_active'], name='records_bud_user_id_13aaf7_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['user', 'is_active'], name='records_bud_user_id_e76c31_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetplan',
            index=models.Index(fields=['start_date', 'end_date'], name='records_bud_start_d_f60fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'status'], name='records_fin_user_id_62fbd5_idx'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'goal_type'], name='records_fin_user_id_4195d3_idx'),
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['target_date'], name='records_fin_target__324f67_idx'),
        ),
        migrations.AddIndex(
            model_name='financialcalendarevent',
            index=models.Index(fields=['user', 'event_date'], name='records_fin_user_id_ace698_idx'),
        ),
        migrations.AddIndex(
            model_name='financialcalendarevent',
            index=models.Index(fields=['user', 'is_completed'], name='records_fin_user_id_34565f_idx'),
        ),
        migrations.AddIndex(
            model_name='financialcalendarevent',
            index=models.Index(fields=['reminder_date'], name='records_fin_reminde_93dea6_idx'),
        ),
        migrations.AddIndex(
            model_name='financialhealthscore',
            index=models.Index(fields=['user', '-calculated_at'], name='records_fin_user_id_43ac0a_idx'),
        ),
        migrations.AddIndex(
            model_name='financialnotification',
            index=models.Index(fields=['user', 'read'], name='records_fin_user_id_d8e270_idx'),
        ),
        migrations.AddIndex(
            model_name='financialnotification',
            index=models.Index(fields=['user', '-created_at'], name='records_fin_user_id_798c29_idx'),
        ),
        migrations.AddIndex(
            model_name='financialnotification',
            index=models.Index(fields=['notification_type', 'priority'], name='records_fin_notific_bd611d_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliocomparison',
            index=models.Index(fields=['user', '-created_at'], name='records_por_user_id_17b7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active'], name='records_rec_user_id_6315f3_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['account', 'next_occurrence'], name='records_rec_account_586e31_idx'),
        ),
        migrations.AddIndex(
            model_name='retirementplan',
            index=models.Index(fields=['user', '-created_at'], name='records_ret_user_id_ebfd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxoptimizationstrategy',
            index=models.Index(fields=['user', 'tax_year'], name='records_tax_user_id_0c9c84_idx'),
        ),
        migrations.AddIndex(
            model_name='taxoptimizationstrategy',
            index=models.Index(fields=['strategy_type', 'is_applied'], name='records_tax_strateg_abb5aa_idx'),
        ),
    ]
