# Generated by Django 5.2.9 on 2025-12-17 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0006_bill_budgetcategory_budgetplan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dark_mode_enabled", models.BooleanField(default=False)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto (System)"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=20)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
    ]
