/* tslint:disable */
/* eslint-disable */
/**
 * The Portfolio Strategist
 * Financia is a financial software (fintech) company that services online users with intuitive, user-friendly financial tools to create, monitor, and advise on budgets, portfolios, and investments, all to promote a simplified, interactive, and reliable approach to easily manage your assets.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * API endpoint to get and update user profile details. Returns all personal details stored in the database.  This endpoint uses token-based authentication (Token or JWT) to avoid CSRF requirements. It\'s designed for API clients (mobile apps) that use token authentication.
     */
    async usersProfileApiPartialUpdateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/users/profile/api/`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * API endpoint to get and update user profile details. Returns all personal details stored in the database.  This endpoint uses token-based authentication (Token or JWT) to avoid CSRF requirements. It\'s designed for API clients (mobile apps) that use token authentication.
     */
    async usersProfileApiPartialUpdate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersProfileApiPartialUpdateRaw(initOverrides);
    }

    /**
     * API endpoint to get and update user profile details. Returns all personal details stored in the database.  This endpoint uses token-based authentication (Token or JWT) to avoid CSRF requirements. It\'s designed for API clients (mobile apps) that use token authentication.
     */
    async usersProfileApiRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/users/profile/api/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * API endpoint to get and update user profile details. Returns all personal details stored in the database.  This endpoint uses token-based authentication (Token or JWT) to avoid CSRF requirements. It\'s designed for API clients (mobile apps) that use token authentication.
     */
    async usersProfileApiRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersProfileApiRetrieveRaw(initOverrides);
    }

    /**
     * API endpoint to get and update user profile details. Returns all personal details stored in the database.  This endpoint uses token-based authentication (Token or JWT) to avoid CSRF requirements. It\'s designed for API clients (mobile apps) that use token authentication.
     */
    async usersProfileApiUpdateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/users/profile/api/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * API endpoint to get and update user profile details. Returns all personal details stored in the database.  This endpoint uses token-based authentication (Token or JWT) to avoid CSRF requirements. It\'s designed for API clients (mobile apps) that use token authentication.
     */
    async usersProfileApiUpdate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.usersProfileApiUpdateRaw(initOverrides);
    }

}
