#!/bin/bash
echo "=========================================="
echo "LOG COLLECTION SCRIPT"
echo "=========================================="
echo ""
echo "This script will help you collect the logs we need."
echo ""
echo "STEP 1: Make sure Metro is running"
echo "  In Terminal 1: cd assets/javascript/mobile && npx react-native start"
echo ""
echo "STEP 2: Build and run the app"
echo "  In Terminal 2: cd assets/javascript/mobile && npx react-native run-ios"
echo ""
echo "STEP 3: Check Xcode Console"
echo "  - Open ios/mobile.xcworkspace in Xcode"
echo "  - Look at Console tab (bottom)"
echo "  - Copy ALL output that starts with [AppDelegate] or [index.js]"
echo ""
echo "STEP 4: Check Metro Terminal"
echo "  - Look at Terminal 1 (Metro bundler)"
echo "  - Copy output that appears when app launches"
echo ""
echo "STEP 5: Share the logs"
echo "  - Paste Xcode console output"
echo "  - Paste Metro bundler output"
echo "  - Any error messages"
echo ""
echo "=========================================="
echo "What to look for:"
echo "=========================================="
echo ""
echo "In Xcode Console, you should see:"
echo "  [AppDelegate] application:didFinishLaunchingWithOptions called"
echo "  [AppDelegate] Module name set to: mobile"
echo "  [AppDelegate] DEBUG: Bundle URL = ..."
echo ""
echo "In Metro Terminal, you should see:"
echo "  BUNDLE  ./index.js"
echo "  LOG  [index.js] SIMPLE VERSION - Starting..."
echo ""
echo "If you DON'T see these, note which ones are missing."
echo ""
