/* tslint:disable */
/* eslint-disable */
/**
 * The Portfolio Strategist
 * Financia is a financial software (fintech) company that services online users with intuitive, user-friendly financial tools to create, monitor, and advise on budgets, portfolios, and investments, all to promote a simplified, interactive, and reliable approach to easily manage your assets.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CookieTokenRefreshResponse
 */
export interface CookieTokenRefreshResponse {
    /**
     * WIll override cookie.
     * @type {string}
     * @memberof CookieTokenRefreshResponse
     */
    refresh?: string;
    /**
     * 
     * @type {string}
     * @memberof CookieTokenRefreshResponse
     */
    readonly access: string;
}

/**
 * Check if a given object implements the CookieTokenRefreshResponse interface.
 */
export function instanceOfCookieTokenRefreshResponse(value: object): value is CookieTokenRefreshResponse {
    if (!('access' in value) || value['access'] === undefined) return false;
    return true;
}

export function CookieTokenRefreshResponseFromJSON(json: any): CookieTokenRefreshResponse {
    return CookieTokenRefreshResponseFromJSONTyped(json, false);
}

export function CookieTokenRefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CookieTokenRefreshResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'refresh': json['refresh'] == null ? undefined : json['refresh'],
        'access': json['access'],
    };
}

  export function CookieTokenRefreshResponseToJSON(json: any): CookieTokenRefreshResponse {
      return CookieTokenRefreshResponseToJSONTyped(json, false);
  }

  export function CookieTokenRefreshResponseToJSONTyped(value?: Omit<CookieTokenRefreshResponse, 'access'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refresh': value['refresh'],
    };
}

