/* tslint:disable */
/* eslint-disable */
/**
 * The Portfolio Strategist
 * Financia is a financial software (fintech) company that services online users with intuitive, user-friendly financial tools to create, monitor, and advise on budgets, portfolios, and investments, all to promote a simplified, interactive, and reliable approach to easily manage your assets.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Custom login serializer that accepts both email and username.
 * Since the app uses email authentication, we prioritize email but also support username.
 * @export
 * @interface CustomLogin
 */
export interface CustomLogin {
    /**
     * 
     * @type {string}
     * @memberof CustomLogin
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomLogin
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomLogin
     */
    password: string;
}

/**
 * Check if a given object implements the CustomLogin interface.
 */
export function instanceOfCustomLogin(value: object): value is CustomLogin {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CustomLoginFromJSON(json: any): CustomLogin {
    return CustomLoginFromJSONTyped(json, false);
}

export function CustomLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomLogin {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'],
    };
}

  export function CustomLoginToJSON(json: any): CustomLogin {
      return CustomLoginToJSONTyped(json, false);
  }

  export function CustomLoginToJSONTyped(value?: CustomLogin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'password': value['password'],
    };
}

