/* tslint:disable */
/* eslint-disable */
/**
 * The Portfolio Strategist
 * Financia is a financial software (fintech) company that services online users with intuitive, user-friendly financial tools to create, monitor, and advise on budgets, portfolios, and investments, all to promote a simplified, interactive, and reliable approach to easily manage your assets.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaidLinkTokenResponse
 */
export interface PlaidLinkTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof PlaidLinkTokenResponse
     */
    linkToken: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidLinkTokenResponse
     */
    expiration: string;
}

/**
 * Check if a given object implements the PlaidLinkTokenResponse interface.
 */
export function instanceOfPlaidLinkTokenResponse(value: object): value is PlaidLinkTokenResponse {
    if (!('linkToken' in value) || value['linkToken'] === undefined) return false;
    if (!('expiration' in value) || value['expiration'] === undefined) return false;
    return true;
}

export function PlaidLinkTokenResponseFromJSON(json: any): PlaidLinkTokenResponse {
    return PlaidLinkTokenResponseFromJSONTyped(json, false);
}

export function PlaidLinkTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidLinkTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'linkToken': json['link_token'],
        'expiration': json['expiration'],
    };
}

  export function PlaidLinkTokenResponseToJSON(json: any): PlaidLinkTokenResponse {
      return PlaidLinkTokenResponseToJSONTyped(json, false);
  }

  export function PlaidLinkTokenResponseToJSONTyped(value?: PlaidLinkTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link_token': value['linkToken'],
        'expiration': value['expiration'],
    };
}

