/* tslint:disable */
/* eslint-disable */
/**
 * The Portfolio Strategist
 * Financia is a financial software (fintech) company that services online users with intuitive, user-friendly financial tools to create, monitor, and advise on budgets, portfolios, and investments, all to promote a simplified, interactive, and reliable approach to easily manage your assets.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaidPublicTokenExchangeRequest
 */
export interface PlaidPublicTokenExchangeRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaidPublicTokenExchangeRequest
     */
    publicToken: string;
}

/**
 * Check if a given object implements the PlaidPublicTokenExchangeRequest interface.
 */
export function instanceOfPlaidPublicTokenExchangeRequest(value: object): value is PlaidPublicTokenExchangeRequest {
    if (!('publicToken' in value) || value['publicToken'] === undefined) return false;
    return true;
}

export function PlaidPublicTokenExchangeRequestFromJSON(json: any): PlaidPublicTokenExchangeRequest {
    return PlaidPublicTokenExchangeRequestFromJSONTyped(json, false);
}

export function PlaidPublicTokenExchangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidPublicTokenExchangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'publicToken': json['public_token'],
    };
}

  export function PlaidPublicTokenExchangeRequestToJSON(json: any): PlaidPublicTokenExchangeRequest {
      return PlaidPublicTokenExchangeRequestToJSONTyped(json, false);
  }

  export function PlaidPublicTokenExchangeRequestToJSONTyped(value?: PlaidPublicTokenExchangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_token': value['publicToken'],
    };
}

