/* tslint:disable */
/* eslint-disable */
/**
 * The Portfolio Strategist
 * Financia is a financial software (fintech) company that services online users with intuitive, user-friendly financial tools to create, monitor, and advise on budgets, portfolios, and investments, all to promote a simplified, interactive, and reliable approach to easily manage your assets.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for JWT authentication.
 * @export
 * @interface PlaidAuthExchangeResponse
 */
export interface PlaidAuthExchangeResponse {
    /**
     * 
     * @type {string}
     * @memberof PlaidAuthExchangeResponse
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAuthExchangeResponse
     */
    refresh: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAuthExchangeResponse
     */
    readonly user: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAuthExchangeResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAuthExchangeResponse
     */
    detail: string;
}

/**
 * Check if a given object implements the PlaidAuthExchangeResponse interface.
 */
export function instanceOfPlaidAuthExchangeResponse(value: object): value is PlaidAuthExchangeResponse {
    if (!('access' in value) || value['access'] === undefined) return false;
    if (!('refresh' in value) || value['refresh'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function PlaidAuthExchangeResponseFromJSON(json: any): PlaidAuthExchangeResponse {
    return PlaidAuthExchangeResponseFromJSONTyped(json, false);
}

export function PlaidAuthExchangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidAuthExchangeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'],
        'refresh': json['refresh'],
        'user': json['user'],
        'status': json['status'],
        'detail': json['detail'],
    };
}

  export function PlaidAuthExchangeResponseToJSON(json: any): PlaidAuthExchangeResponse {
      return PlaidAuthExchangeResponseToJSONTyped(json, false);
  }

  export function PlaidAuthExchangeResponseToJSONTyped(value?: Omit<PlaidAuthExchangeResponse, 'user'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access': value['access'],
        'refresh': value['refresh'],
        'status': value['status'],
        'detail': value['detail'],
    };
}

