# Generated by Django 5.2.9 on 2025-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatmessage_attachment_chatmessage_attachment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AICredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI (GPT)"),
                            ("anthropic", "Anthropic (Claude)"),
                            ("google", "Google (Gemini)"),
                            ("xai", "xAI (Grok)"),
                            ("cursor", "Cursor IDE"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional note to help identify this key",
                        max_length=128,
                    ),
                ),
                ("api_key", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Credential",
                "verbose_name_plural": "AI Credentials",
                "ordering": ["provider"],
            },
        ),
    ]
